project_id = "wjmkijvckvnrrsjzgwge"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-upgrade-email]
verify_jwt = false

[functions.send-waitlist-confirmation]
verify_jwt = false

[functions.send-trial-expiry-reminder]
verify_jwt = false
